/**
 * Jira & Linear Voice-to-Action Execution Engine
 * Transforms voice standup blockers and tasks into structured Jira REST API payloads
 * and Linear Issue payloads, keeping task boards in sync.
 */

export function buildJiraIssuePayload(task, projectKey = 'ENG') {
  return {
    fields: {
      project: { key: projectKey },
      summary: task.title || 'Standup Task',
      description: {
        type: 'doc',
        version: 1,
        content: [
          {
            type: 'paragraph',
            content: [
              {
                type: 'text',
                text: task.description || 'Auto-generated from mvp_PRO voice update.'
              }
            ]
          }
        ]
      },
      issuetype: { name: task.source === 'ai_blocker' ? 'Bug' : 'Task' },
      priority: { name: task.priority === 'critical' ? 'Highest' : task.priority === 'high' ? 'High' : 'Medium' }
    }
  };
}

export function buildLinearIssuePayload(task, teamId = 'team-eng') {
  return {
    teamId: teamId,
    title: task.title,
    description: task.description || 'Generated by mvp_PRO',
    priority: task.priority === 'critical' ? 1 : task.priority === 'high' ? 2 : 3
  };
}

/**
 * Dispatch Jira Ticket creation (or mock return if no key configured)
 */
export async function syncTaskToJira(task, jiraDomain = process.env.JIRA_DOMAIN, apiToken = process.env.JIRA_API_TOKEN) {
  const jiraPayload = buildJiraIssuePayload(task);

  if (jiraDomain && apiToken) {
    try {
      const res = await fetch(`https://${jiraDomain}/rest/api/3/issue`, {
        method: 'POST',
        headers: {
          'Authorization': `Basic ${Buffer.from(`api:${apiToken}`).toString('base64')}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(jiraPayload)
      });

      if (res.ok) {
        const data = await res.json();
        return { success: true, issue_key: data.key, url: `https://${jiraDomain}/browse/${data.key}` };
      }
    } catch (err) {
      console.warn('Jira API dispatch failed:', err.message);
    }
  }

  // Simulation mode
  const mockKey = `ENG-${Math.floor(1000 + Math.random() * 9000)}`;
  return {
    success: true,
    simulated: true,
    issue_key: mockKey,
    url: `https://jira.acme.atlassian.net/browse/${mockKey}`,
    payload: jiraPayload
  };
}

/**
 * Dispatch Linear Issue creation (or mock return)
 */
export async function syncTaskToLinear(task, linearApiKey = process.env.LINEAR_API_KEY) {
  const linearPayload = buildLinearIssuePayload(task);

  if (linearApiKey) {
    try {
      const query = `
        mutation IssueCreate($input: IssueCreateInput!) {
          issueCreate(input: $input) {
            success
            issue { id title identifier url }
          }
        }
      `;
      const res = await fetch('https://api.linear.app/graphql', {
        method: 'POST',
        headers: {
          'Authorization': linearApiKey,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ query, variables: { input: linearPayload } })
      });

      if (res.ok) {
        const data = await res.json();
        if (data?.data?.issueCreate?.success) {
          return { success: true, issue: data.data.issueCreate.issue };
        }
      }
    } catch (err) {
      console.warn('Linear API dispatch failed:', err.message);
    }
  }

  // Simulation mode
  const mockId = `ENG-${Math.floor(100 + Math.random() * 900)}`;
  return {
    success: true,
    simulated: true,
    issue_key: mockId,
    url: `https://linear.app/acme/issue/${mockId}`,
    payload: linearPayload
  };
}
